package com.ej.hgj.model;

public class PoBindListDo {
	
    private String custId;

    private String poSeqId;

    private String stat;

    private String authCorpId;

    private String ewUsrId; 
    
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column po_bind_list.CUST_ID
     *
     * @param custId the value for po_bind_list.CUST_ID
     *
     * @mbg.generated Thu Aug 06 14:25:46 CST 2020
     */
    public void setCustId(String custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column po_bind_list.PO_SEQ_ID
     *
     * @return the value of po_bind_list.PO_SEQ_ID
     *
     * @mbg.generated Thu Aug 06 14:25:46 CST 2020
     */
    public String getPoSeqId() {
        return poSeqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column po_bind_list.PO_SEQ_ID
     *
     * @param poSeqId the value for po_bind_list.PO_SEQ_ID
     *
     * @mbg.generated Thu Aug 06 14:25:46 CST 2020
     */
    public void setPoSeqId(String poSeqId) {
        this.poSeqId = poSeqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column po_bind_list.STAT
     *
     * @return the value of po_bind_list.STAT
     *
     * @mbg.generated Thu Aug 06 14:25:46 CST 2020
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column po_bind_list.STAT
     *
     * @param stat the value for po_bind_list.STAT
     *
     * @mbg.generated Thu Aug 06 14:25:46 CST 2020
     */
    public void setStat(String stat) {
        this.stat = stat;
    }

	public String getAuthCorpId() {
		return authCorpId;
	}

	public void setAuthCorpId(String authCorpId) {
		this.authCorpId = authCorpId;
	}

	public String getEwUsrId() {
		return ewUsrId;
	}

	public void setEwUsrId(String ewUsrId) {
		this.ewUsrId = ewUsrId;
	}
    
    
}