package com.ej.hgj.model;

public class SuiteConfInfoDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUITE_CONF_INFO.SUITE_ID
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    private String suiteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUITE_CONF_INFO.SUITE_NAME
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    private String suiteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUITE_CONF_INFO.SUITE_TICKET
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    private String suiteTicket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUITE_CONF_INFO.SUITE_SECRET
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    private String suiteSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUITE_CONF_INFO.SUITE_TOKEN
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    private String suiteToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUITE_CONF_INFO.CREATE_TOKEN_TIME
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    private String createTokenTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUITE_CONF_INFO.TOKEN_EXPIRE
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    private Integer tokenExpire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUITE_CONF_INFO.STAT
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    private String stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUITE_CONF_INFO.SUITE_ID
     *
     * @return the value of SUITE_CONF_INFO.SUITE_ID
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public String getSuiteId() {
        return suiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUITE_CONF_INFO.SUITE_ID
     *
     * @param suiteId the value for SUITE_CONF_INFO.SUITE_ID
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public void setSuiteId(String suiteId) {
        this.suiteId = suiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUITE_CONF_INFO.SUITE_NAME
     *
     * @return the value of SUITE_CONF_INFO.SUITE_NAME
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public String getSuiteName() {
        return suiteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUITE_CONF_INFO.SUITE_NAME
     *
     * @param suiteName the value for SUITE_CONF_INFO.SUITE_NAME
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public void setSuiteName(String suiteName) {
        this.suiteName = suiteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUITE_CONF_INFO.SUITE_TICKET
     *
     * @return the value of SUITE_CONF_INFO.SUITE_TICKET
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public String getSuiteTicket() {
        return suiteTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUITE_CONF_INFO.SUITE_TICKET
     *
     * @param suiteTicket the value for SUITE_CONF_INFO.SUITE_TICKET
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public void setSuiteTicket(String suiteTicket) {
        this.suiteTicket = suiteTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUITE_CONF_INFO.SUITE_SECRET
     *
     * @return the value of SUITE_CONF_INFO.SUITE_SECRET
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public String getSuiteSecret() {
        return suiteSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUITE_CONF_INFO.SUITE_SECRET
     *
     * @param suiteSecret the value for SUITE_CONF_INFO.SUITE_SECRET
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public void setSuiteSecret(String suiteSecret) {
        this.suiteSecret = suiteSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUITE_CONF_INFO.SUITE_TOKEN
     *
     * @return the value of SUITE_CONF_INFO.SUITE_TOKEN
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public String getSuiteToken() {
        return suiteToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUITE_CONF_INFO.SUITE_TOKEN
     *
     * @param suiteToken the value for SUITE_CONF_INFO.SUITE_TOKEN
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public void setSuiteToken(String suiteToken) {
        this.suiteToken = suiteToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUITE_CONF_INFO.CREATE_TOKEN_TIME
     *
     * @return the value of SUITE_CONF_INFO.CREATE_TOKEN_TIME
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public String getCreateTokenTime() {
        return createTokenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUITE_CONF_INFO.CREATE_TOKEN_TIME
     *
     * @param createTokenTime the value for SUITE_CONF_INFO.CREATE_TOKEN_TIME
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public void setCreateTokenTime(String createTokenTime) {
        this.createTokenTime = createTokenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUITE_CONF_INFO.TOKEN_EXPIRE
     *
     * @return the value of SUITE_CONF_INFO.TOKEN_EXPIRE
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public Integer getTokenExpire() {
        return tokenExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUITE_CONF_INFO.TOKEN_EXPIRE
     *
     * @param tokenExpire the value for SUITE_CONF_INFO.TOKEN_EXPIRE
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public void setTokenExpire(Integer tokenExpire) {
        this.tokenExpire = tokenExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUITE_CONF_INFO.STAT
     *
     * @return the value of SUITE_CONF_INFO.STAT
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUITE_CONF_INFO.STAT
     *
     * @param stat the value for SUITE_CONF_INFO.STAT
     *
     * @mbg.generated Wed Mar 11 18:24:15 CST 2020
     */
    public void setStat(String stat) {
        this.stat = stat;
    }
}