package com.ej.hgj.model;

public class UsrInfoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.CUST_ID
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.SHORT_NAME
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.USR_NAME
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String usrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.EW_CORP_ID
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String ewCorpId;
    
    private String pubOrgId;

    private String pubAppId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.USR_STAT
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String usrStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.USR_PROV
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String usrProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.USR_AREA
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String usrArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.OPEN_DATE
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String openDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.OPEN_TIME
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.BRANCH_ID
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.BDEP_ID
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String bdepId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.SALE_ID
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String saleId;
    
    private String poSeqId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.MAG_MP
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String magMp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.MAG_EMAIL
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String magEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.MAG_TEL
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String magTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.MAG_NAME
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String magName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.URGENT_MP
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String urgentMp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.LOGIN_ACTION
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String loginAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_info.UPD_DATETIME
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    private String updDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.CUST_ID
     *
     * @return the value of usr_info.CUST_ID
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.CUST_ID
     *
     * @param custId the value for usr_info.CUST_ID
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setCustId(String custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.SHORT_NAME
     *
     * @return the value of usr_info.SHORT_NAME
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.SHORT_NAME
     *
     * @param shortName the value for usr_info.SHORT_NAME
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.USR_NAME
     *
     * @return the value of usr_info.USR_NAME
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getUsrName() {
        return usrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.USR_NAME
     *
     * @param usrName the value for usr_info.USR_NAME
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setUsrName(String usrName) {
        this.usrName = usrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.EW_CORP_ID
     *
     * @return the value of usr_info.EW_CORP_ID
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getEwCorpId() {
        return ewCorpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.EW_CORP_ID
     *
     * @param ewCorpId the value for usr_info.EW_CORP_ID
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setEwCorpId(String ewCorpId) {
        this.ewCorpId = ewCorpId;
    }

    public String getPubOrgId() {
		return pubOrgId;
	}

	public void setPubOrgId(String pubOrgId) {
		this.pubOrgId = pubOrgId;
	}

	public String getPubAppId() {
		return pubAppId;
	}

	public void setPubAppId(String pubAppId) {
		this.pubAppId = pubAppId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.USR_STAT
     *
     * @return the value of usr_info.USR_STAT
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getUsrStat() {
        return usrStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.USR_STAT
     *
     * @param usrStat the value for usr_info.USR_STAT
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setUsrStat(String usrStat) {
        this.usrStat = usrStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.USR_PROV
     *
     * @return the value of usr_info.USR_PROV
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getUsrProv() {
        return usrProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.USR_PROV
     *
     * @param usrProv the value for usr_info.USR_PROV
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setUsrProv(String usrProv) {
        this.usrProv = usrProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.USR_AREA
     *
     * @return the value of usr_info.USR_AREA
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getUsrArea() {
        return usrArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.USR_AREA
     *
     * @param usrArea the value for usr_info.USR_AREA
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setUsrArea(String usrArea) {
        this.usrArea = usrArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.OPEN_DATE
     *
     * @return the value of usr_info.OPEN_DATE
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.OPEN_DATE
     *
     * @param openDate the value for usr_info.OPEN_DATE
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setOpenDate(String openDate) {
        this.openDate = openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.OPEN_TIME
     *
     * @return the value of usr_info.OPEN_TIME
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.OPEN_TIME
     *
     * @param openTime the value for usr_info.OPEN_TIME
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setOpenTime(String openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.BRANCH_ID
     *
     * @return the value of usr_info.BRANCH_ID
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.BRANCH_ID
     *
     * @param branchId the value for usr_info.BRANCH_ID
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.BDEP_ID
     *
     * @return the value of usr_info.BDEP_ID
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getBdepId() {
        return bdepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.BDEP_ID
     *
     * @param bdepId the value for usr_info.BDEP_ID
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setBdepId(String bdepId) {
        this.bdepId = bdepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.SALE_ID
     *
     * @return the value of usr_info.SALE_ID
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.SALE_ID
     *
     * @param saleId the value for usr_info.SALE_ID
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setSaleId(String saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.MAG_MP
     *
     * @return the value of usr_info.MAG_MP
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getMagMp() {
        return magMp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.MAG_MP
     *
     * @param magMp the value for usr_info.MAG_MP
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setMagMp(String magMp) {
        this.magMp = magMp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.MAG_EMAIL
     *
     * @return the value of usr_info.MAG_EMAIL
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getMagEmail() {
        return magEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.MAG_EMAIL
     *
     * @param magEmail the value for usr_info.MAG_EMAIL
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setMagEmail(String magEmail) {
        this.magEmail = magEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.MAG_TEL
     *
     * @return the value of usr_info.MAG_TEL
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getMagTel() {
        return magTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.MAG_TEL
     *
     * @param magTel the value for usr_info.MAG_TEL
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setMagTel(String magTel) {
        this.magTel = magTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.MAG_NAME
     *
     * @return the value of usr_info.MAG_NAME
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getMagName() {
        return magName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.MAG_NAME
     *
     * @param magName the value for usr_info.MAG_NAME
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setMagName(String magName) {
        this.magName = magName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.URGENT_MP
     *
     * @return the value of usr_info.URGENT_MP
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getUrgentMp() {
        return urgentMp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.URGENT_MP
     *
     * @param urgentMp the value for usr_info.URGENT_MP
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setUrgentMp(String urgentMp) {
        this.urgentMp = urgentMp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.LOGIN_ACTION
     *
     * @return the value of usr_info.LOGIN_ACTION
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getLoginAction() {
        return loginAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.LOGIN_ACTION
     *
     * @param loginAction the value for usr_info.LOGIN_ACTION
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setLoginAction(String loginAction) {
        this.loginAction = loginAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_info.UPD_DATETIME
     *
     * @return the value of usr_info.UPD_DATETIME
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public String getUpdDatetime() {
        return updDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_info.UPD_DATETIME
     *
     * @param updDatetime the value for usr_info.UPD_DATETIME
     *
     * @mbggenerated Thu Aug 06 14:32:14 CST 2020
     */
    public void setUpdDatetime(String updDatetime) {
        this.updDatetime = updDatetime;
    }

    public String getPoSeqId() {
        return poSeqId;
    }

    public void setPoSeqId(String poSeqId) {
        this.poSeqId = poSeqId;
    }
    
}